name: Practice Brackets

on:
    push:
        branches: [main]

env:
    TIMEZONE: 'America/New_York'
    DATE_START: '2025-01-01'
    DATE_END: '2025-01-31'

jobs:
    check-date:
        runs-on: ubuntu-22.04

        steps:
            - name: Clone Repository
              uses: actions/checkout@v4

            - name: Configure Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: 2.1.4

            - name: Is Practice Bracket Date Range
              id: date-check
              run: deno task workflow:date-check $TIMEZONE $DATE_START $DATE_END

    run-bracket:
        needs: check-date

        runs-on: ubuntu-22.04
        permissions:
            contents: write

        steps:
            - name: Clone Repository
              uses: actions/checkout@v4

            - name: Configure Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: 2.1.4

            - name: Download Game Engine
              run: |
                  mkdir ./.bin
                  wget --output-document ./.bin/dotsandboxes-linux https://github.com/PSH-Computing-AI-club/competition-spring-2025-dotsandboxes/releases/latest/download/dotsandboxes-linux
                  chmod +x ./.bin/dotsandboxes-linux

            - name: Clone Competitor Repositories
              env:
                  APP_ID: ${{ secrets.APP_ID }}
                  APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

              run: deno task bracket:clone

            - name: Run Bracket
              run: deno task bracket:run

            - name: Visualize Bracket
              run: deno task bracket:visualize

            - name: Upload Visualization as Artifact
              uses: actions/upload-pages-artifact@v3
              id: visualization-artifact
              with:
                  path: ./dist/www

    deploy-artifact:
        needs: run-bracket

        runs-on: ubuntu-22.04
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        permissions:
            id-token: write
            pages: write

        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
              id: visualization-artifact
